version: '3'

services:

  postgres:
    image: 'postgres:14.5'
    container_name: "postgres_isolation"
    restart: always
    environment:
      - POSTGRES_DB=isolation_levels
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      - fullstack
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks:
  fullstack:
    driver: bridge

# Start: docker-compose -f pg-docker-compose.yml up
# Stop: docker-compose -f pg-docker-compose.yml down