services:

  postgres:
    image: postgres:14.5
    container_name: postgres_isolation
    restart: "no"
    environment:
      POSTGRES_DB: isolation_levels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5432"
    networks:
      - fullstack
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d

networks:
  fullstack:
    driver: bridge

volumes:
  postgres_data: